---
- name: Installing and configuring Docker
  hosts: all
  become: yes
  vars_files:
    - providers/other/vars/other_vars.yml
  roles:
    - { role: docker, tags: ["docker"] }

- name: Setting up Rancher Server
  hosts: all
  vars_files:
    - providers/other/vars/other_vars.yml
  become: yes
  roles:
    - { role: rancher, tags: ["rancher"] }